name: CI/CD for MedInsurance Frontend

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  build-docker:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t medinsurancefront:latest .
          
      - name: Save Docker Image
        run: |
          docker save medinsurancefront:latest > medinsurancefront.tar
          
      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medinsurancefront-docker-image
          path: medinsurancefront.tar
          retention-days: 7